<a href="https://colab.research.google.com/github/gregory-lebl/colab-cesi-data-science/blob/day-2/lec24_transformed.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import scipy as sp
import plotly.express as px
import seaborn as sns


# Travailler avec des données de haute dimension

Dans les cellules suivantes, nous utiliserons des outils de visualisation pour aller aussi loin que possible dans la visualisation du jeu de données MPG dans un espace à haute dimension :


In [2]:
mpg = sns.load_dataset("mpg").dropna()
mpg.head()


mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [3]:
px.histogram(mpg, x="displacement")


In [4]:
px.scatter(mpg, x="displacement", y="horsepower")

In [5]:
fig = px.scatter_3d(mpg, x="displacement", y="horsepower", z="weight",
                    width=800, height=800)
fig.update_traces(marker=dict(size=3))


In [6]:
fig = px.scatter_3d(mpg, x="displacement",
                    y="horsepower",
                    z="weight",
                    color="model_year",
                    width=800, height=800,
                    opacity=.7)
fig.update_traces(marker=dict(size=5))


In [7]:
fig = px.scatter_3d(mpg, x="displacement",
                    y="horsepower",
                    z="weight",
                    color="model_year",
                    size="mpg",
                    symbol="origin",
                    width=900, height=800,
                    opacity=.7)
# hide color scale legend on the plotly fig
fig.update_layout(coloraxis_showscale=False)


In [8]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2,)

components = pca.fit_transform(mpg[["displacement", "horsepower", "weight", "model_year"]])
mpg[["z1", "z2"]] = components
mpg.head()


mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name          z1         z2  
0          70    usa  chevrolet chevelle malibu  536.436716  50.754633  
1          70    usa          buick skylark 320  730.333026  79.063105  
2          70    usa         plymouth satellite  470.971839  75.338465  
3          70    usa              amc rebel sst  466.393030  62.448249  
4          70    usa                ford torino  481.657494  55.643203

In [9]:
px.scatter(mpg, x="z1", y="z2", color="model_year", hover_data=["displacement", "horsepower", "weight", "name"])


# SVD

In [10]:
# Seed for reproducibility
np.random.seed(42)

# Generate 100 rows of random data for width and height
width = np.random.randint(1, 10, size=100)
height = np.random.randint(1, 10, size=100)

# Calculate area and perimeter
area = width * height
perimeter = 2 * (width + height)

# Create a DataFrame
df = pd.DataFrame({
    'width': width,
    'height': height,
    'area': area,
    'perimeter': perimeter
})

# Display the DataFrame
print(df)

# Optionally save t
rectangle = df


    width  height  area  perimeter
0       7       3    21         20
1       4       5    20         18
2       8       3    24         22
3       5       1     5         12
4       7       5    35         24
..    ...     ...   ...        ...
95      3       1     3          8
96      8       8    64         32
97      6       7    42         26
98      3       2     6         10
99      1       8     8         18

[100 rows x 4 columns]


In [11]:
px.scatter_3d(rectangle, x="width", y="height", z="area",
              width=800, height=800)


In [12]:
X = rectangle - np.mean(rectangle, axis = 0)
X


width  height   area  perimeter
0    1.68   -1.82  -5.69      -0.28
1   -1.32    0.18  -6.69      -2.28
2    2.68   -1.82  -2.69       1.72
3   -0.32   -3.82 -21.69      -8.28
4    1.68    0.18   8.31       3.72
..    ...     ...    ...        ...
95  -2.32   -3.82 -23.69     -12.28
96   2.68    3.18  37.31      11.72
97   0.68    2.18  15.31       5.72
98  -2.32   -2.82 -20.69     -10.28
99  -4.32    3.18 -18.69      -2.28

[100 rows x 4 columns]

In [13]:
U, S, Vt = np.linalg.svd(X, full_matrices = False)


In [14]:
print("Shape of U", U.shape)
print("Shape of S", S.shape)
print("Shape of Vt", Vt.shape)


Shape of U (100, 4)
Shape of S (4,)
Shape of Vt (4, 4)


In [15]:
S


array([2.19021118e+02, 2.51026227e+01, 2.37839919e+01, 7.07267933e-15])

In [16]:
np.isclose(S[3], 0)


True

In [17]:
S.round(5)


array([219.02112,  25.10262,  23.78399,   0.     ])

In [18]:
Sm = np.diag(S)
Sm


array([[2.19021118e+02, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 2.51026227e+01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.37839919e+01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 7.07267933e-15]])

In [19]:
pd.DataFrame(U).head(5)


0         1         2         3
0  0.024642 -0.110201 -0.056535 -0.743871
1  0.032460  0.011529  0.044111 -0.628156
2  0.008334 -0.153658 -0.066202 -0.010045
3  0.106845 -0.040768 -0.094409  0.016026
4 -0.041912 -0.040482 -0.028199  0.004047

In [20]:
pd.DataFrame(Vt)


0         1         2         3
0 -0.086898 -0.087549 -0.929008 -0.348896
1 -0.521422  0.133187  0.327831 -0.776471
2 -0.525474  0.728115 -0.171672  0.405282
3  0.666667  0.666667  0.000000 -0.333333

In [21]:
Vt.shape


(4, 4)

In [22]:
display(pd.DataFrame(U @ Sm @ Vt).head(5))
display(pd.DataFrame(X).head(5))


0     1      2     3
0  1.68 -1.82  -5.69 -0.28
1 -1.32  0.18  -6.69 -2.28
2  2.68 -1.82  -2.69  1.72
3 -0.32 -3.82 -21.69 -8.28
4  1.68  0.18   8.31  3.72

width  height   area  perimeter
0   1.68   -1.82  -5.69      -0.28
1  -1.32    0.18  -6.69      -2.28
2   2.68   -1.82  -2.69       1.72
3  -0.32   -3.82 -21.69      -8.28
4   1.68    0.18   8.31       3.72

In [23]:
X = rectangle - np.mean(rectangle, axis = 0)
X.head(10)


width  height   area  perimeter
0   1.68   -1.82  -5.69      -0.28
1  -1.32    0.18  -6.69      -2.28
2   2.68   -1.82  -2.69       1.72
3  -0.32   -3.82 -21.69      -8.28
4   1.68    0.18   8.31       3.72
5  -2.32    2.18  -5.69      -0.28
6   1.68    2.18  22.31       7.72
7   2.68    4.18  45.31      13.72
8  -0.32   -1.82 -11.69      -4.28
9  -1.32    2.18   1.31       1.72

In [24]:
Xstd = X / np.std(X, axis = 0)


In [25]:
U, S, Vt = np.linalg.svd(X, full_matrices = False)


In [26]:
pd.DataFrame(np.diag(S))


0          1          2             3
0  219.021118   0.000000   0.000000  0.000000e+00
1    0.000000  25.102623   0.000000  0.000000e+00
2    0.000000   0.000000  23.783992  0.000000e+00
3    0.000000   0.000000   0.000000  7.072679e-15

In [27]:
pd.DataFrame(np.round(S**2 / X.shape[0], 2))


0
0  479.70
1    6.30
2    5.66
3    0.00

In [28]:
U, S, Vt = np.linalg.svd(Xstd, full_matrices = False)


In [29]:
pd.DataFrame(np.round(S**2 / X.shape[0], 2))


0
0  3.08
1  0.85
2  0.07
3  0.00

In [30]:
Z = U[:, :2] @ np.diag(S[:2])
pd.DataFrame(Z).head()


0         1
0  0.202043 -0.948314
1  0.530966  0.404602
2 -0.185823 -1.219145
3  1.867004 -0.947964
4 -0.796291 -0.405225

In [31]:
Z = Xstd.to_numpy() @ Vt.T[:,:2]
pd.DataFrame(Z).head()


0         1
0  0.202043 -0.948314
1  0.530966  0.404602
2 -0.185823 -1.219145
3  1.867004 -0.947964
4 -0.796291 -0.405225

In [32]:
px.scatter(x=Z[:, 0], y=Z[:, 1])


In [33]:
pca = PCA(2)
pd.DataFrame(pca.fit_transform(rectangle)).head(5)


0         1
0  -5.397096  2.766336
1  -7.109492 -0.289415
2  -1.825383  3.857206
3 -23.401282  1.023394
4   9.179695  1.016211

In [34]:
pd.DataFrame(pca.fit_transform(X)).head(5)


0         1
0  -5.397096  2.766336
1  -7.109492 -0.289415
2  -1.825383  3.857206
3 -23.401282  1.023394
4   9.179695  1.016211

In [35]:
pd.DataFrame(pca.fit_transform(Xstd)).head(5)


0         1
0 -0.202043 -0.948314
1 -0.530966  0.404602
2  0.185823 -1.219145
3 -1.867004 -0.947964
4  0.796291 -0.405225

In [36]:
pd.DataFrame(np.cov(Z.T))


0             1
0  3.114190e+00  2.572106e-16
1  2.572106e-16  8.555627e-01

In [37]:
rectangle.head()


width  height  area  perimeter
0      7       3    21         20
1      4       5    20         18
2      8       3    24         22
3      5       1     5         12
4      7       5    35         24

In [38]:
k = 2
U, S, Vt = np.linalg.svd(Xstd, full_matrices = False)
scaling = np.diag(np.std(X, axis = 0))
# scaling = np.eye(X.shape[1])
Z = U[:,:k] @ np.diag(S[:k])

rectangle_hat = pd.DataFrame(
    (Z @ Vt[:k, :]) @ scaling + np.mean(rectangle, axis = 0).to_numpy(),
    columns = rectangle.columns)

display(rectangle_hat.head(3))

fig = px.scatter_3d(rectangle, x="width", y="height", z="area",
                    width=800, height=800)
fig.add_scatter3d(x=rectangle_hat["width"], y=rectangle_hat["height"], z=rectangle_hat["area"],
                  mode="markers", name = "approximation")


width    height       area  perimeter
0  6.860274  2.852990  24.228986  19.426528
1  3.967272  4.965565  20.756333  17.865674
2  7.802330  2.792025  28.568040  21.188711


ΣΣ is a little different in NumPy. Since the only useful values in the diagonal matrix ΣΣ are the singular values on the diagonal axis, only those values are returned and they are stored in an array.
Our rectangle_data has a rank of 33, so we should have 3 non-zero singular values, sorted from largest to smallest.








Hmm, looks like are four diagonal entries are not zero. What happened?
It turns out there were some numerical rounding errors, but the last value is so small (10−1510−15) that it's practically 00.






If we want the diagonal elements:



Examining U:



Finally, V⊤V⊤:







To check that this SVD is a valid decomposition, we can reverse it.





PCA with SVD¶Step 1: Center the Data Matrix XX¶



In some situations where the units are on different scales it is useful to normalize the data before performing SVD.
This can be done by dividing each column by its standard deviation.



Step 2: Get the SVD of centered XX¶







Examining the singular values:





Computing the contribution to the total variance:



Much of the variance is in the first dimension.  This is likely because the area is much larger than the other dimensions. Let's examine the standardized version.




Now we see that most of the variance is in the first two dimensions which makes sense since rectangles are largely described by two numbers.









Step 3 Computing Approximations to the Data¶Let's try to approximate this data in two dimensions






Using Z=U∗SZ=U∗S¶



Comparing to scikit learn



Also notice that the covariance of the transformed diagonalized.




Lower Rank Approximation of X¶




Lower Rank Approximation of X¶








Let's now try to recover X from our approximation:



